<?php

	$url[] = "http://www.SaLearningSchool.com/";
	$url[] = "http://www.PlayAndScore.com/";

	$url[] = "http://www.ShopForSoul.com/";
	$url[] = "http://www.GameForSoul.com/";
	$url[] = "http://www.ClassicalArticles.com/";
	$url[] = "http://www.eBooksArchieve.com/";
	$url[] = "http://www.VisitorsShop.com/";
	$url[] = "http://www.FlyerEmailer.com/";

	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=1&category=Operating Systems";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=2&category=Database Systems";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=3&category=Query Optimization";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=4&category=Programming the Printers";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=5&category=MySQL";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=6&category=DBMS Theory";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=7&category=FireBird";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=8&category=Web-Servers";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=10&category=HTML and CSS";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=11&category=IBM DB 2";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=13&category=Ajax and Javascript";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=14&category=Software Version Control";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=15&category=Coding Style";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=16&category=PHP";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=17&category=Payment Processing System";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=18&category=Dot Net Windows Applications";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=19&category=Dot Net Web Applications";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=20&category=Dot Net Solution Architecture";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=21&category=Software Engineering and Project Management";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=22&category=Software Testing";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=24&category=Dot Net XML WebServices Server Components";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=25&category=Object Oriented Design";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=26&category=Linux/Unix - Software Development";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=27&category=Web-Hosting";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=28&category=Internet and Online Business";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=29&category=Web Servers";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=30&category=Project Management";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=32&category=Java";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=34&category=IT-JOB";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=37&category=JSP";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=38&category=SQL Server";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=39&category=POSTGRESQL";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=40&category=Oracle";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=41&category=Employment Laws";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=42&category=Crystal Report";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=43&category=Software Architecture";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=44&category=Data Warehousing and Business Intelligence";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=45&category=Miscellaneous";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=48&category=Hibernate";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=49&category=Workplace";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=51&category=Management";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=52&category=Certification";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=53&category=Security";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=54&category=Software Security";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=56&category=UML";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=58&category=Software Documentation";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=59&category=Computer Games";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=61&category=IDE";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=62&category=Human Computer Interaction";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=63&category=SAP";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=64&category=Security";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=65&category=Ajax";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=66&category=Business Analysis";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=67&category=Business Curriculam";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=68&category=Computer Hardware Engineering";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=69&category=Multimedia";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=70&category=Telecommunications";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=71&category=ACM Programming Contest";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=72&category=Software Development Domains";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=73&category=Microsoft Project";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=74&category=Linux/Unix";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=75&category=Simulation";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=76&category=Career";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=77&category=C++";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=78&category=Software Maintenance";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=79&category=Web Site Development";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=80&category=Adobe Flex";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=81&category=Microsoft Visual Studio";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=82&category=Bangladesh";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=83&category=Step by Step Software Development";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=85&category=Embedded Software Development";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=86&category=Search Engine Optimization";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=87&category=Software Development Domain";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=88&category=Software";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=89&category=Cell Phone";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=90&category=Microsoft Access";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=91&category=Business Development";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=92&category=Digital Camera";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=96&category=Advertising";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=97&category=VOIP";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=98&category=Ebay Business";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=99&category=Adsense";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=100&category=Data Recovery";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=101&category=Hardware";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=102&category=Networks";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=103&category=Security";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=105&category=Operating Systems";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=106&category=Databases";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=107&category=Information Technology";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=108&category=E-Learning";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=109&category=Intranet";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=110&category=Programming";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=111&category=Sensor Network";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=112&category=Grid Computing";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=113&category=Content Management Systems";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=114&category=Computer Networks";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=115&category=Computer Simulation";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=118&category=Virtualization";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=119&category=Book Reviews";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=120&category=Shopping and Product Reviews";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=121&category=Arts and Entertainment";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=124&category=Everyday";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=126&category=Miscellaneous";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=127&category=Ruby on Rails";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=128&category=Mathematics";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=129&category=Computer and Internet";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=130&category=ENTERPRIGE NETWORKING";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=131&category=COUPUTER SECURITY";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=132&category=Integration Technologies";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=135&category=kobita";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=138&category=Business-Finance";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=143&category=medical topics";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=144&category=Creative and Expressive Play";
	$url[] = "http://www.SaLearningSchool.com/index.php?table=Articles&categoryID=146&category=Computer";

?>